<?php
/**
 * Asset file for Heartland blocks script.
 * Auto-generated by the build process.
 */

return array(
	'dependencies' => array( 'react', 'wc-blocks-registry', 'wc-settings', 'wp-element', 'wp-html-entities', 'wp-i18n' ),
	'version'      => '1.0.0',
);
